### PR TITLE
[Feature 51, 53, and 72] Janky chat fixes for demo

### LINKED ISSUE #51: [Feature 51] One-on-one chat display displays conversation partner display name at the top
One-on-one chat display takes and uses information from previous pages. 
- One-on-one chat display displays conversation partner display name at the top, rather than being hardcoded to a temporary constant. 
- stores and uses the actual current user's userID, and the actual conversation partner's userID.

### LINKED ISSUE #53: [Feature 53] One-on-one chat screen: add functionality to navigation buttons
- Screen has a back button--not connected to anything atm; made an issue. 
- Screen has a place for entering text and a send button--not connected to anything atm

### LINKED ISSUE #72: [Feature 72] Send button clears input text box
chatInput should clear once the button is pressed, so that people don't have to delete the previous message to send a new one
shouldn't send empty messages

### PR DESCRIPTION
**Pull request by navarhontes**
Janky fixes made for issues: 
* Closes #53; 
finally figured out how to make the back button work. Used super.onBackPressed() instead of this.onBackPressed(). Still don't know why it works, but it works and that's good enough for now. 
* Closes #72; 
turned out to be a one-liner. You just call this.clear on the EditText view. 
* Closes #51; 
decided to just uses intent and pass it from Kresimir's fragment since I don't have time to learn and test database functions. Pulled it from Kresimir's fragment by making the local LikeListResponseModel attribute that's initialized when the screen is made into a class attribute, and pulling the info from that model. 
* As a result of me unhardcoding the userID without implementing a database connection, it looked like sent messages didn't display properly. Still having trouble with database implementation, so I'm just making it _look_ like it works by hardcoding it with Jack's userID. 
* Dealt with some warnings

### CODE REVIEW

File: app/src/main/java/com/courseproject/tindar/ui/chat/ChatActivity.java [hunk 1]
```diff
@@ -170,7 +171,12 @@ public void sentMessage(View v){
         MessageModel newMessage = new TindarMessage(input, new Timestamp(System.currentTimeMillis()),
                 this.userId, this.otherUserId);
         this.loadedMessages.add(newMessage);
+        this.chatInput.getText().clear();
 
         this.adapter.notifyDataSetChanged();
     }
+
+    public void backButtonPressed(View v){
```
Comment (jenniferjinyoungyang) [inline app/src/main/java/com/courseproject/tindar/ui/chat/ChatActivity.java:179]: This is not override?

**Comment by jenniferjinyoungyang** [comment]
Given that database implementation will clean out all the dummy data hard-coded in frontend, looks good to me. Just have one small question above.

File: app/src/main/java/com/courseproject/tindar/ui/chat/ChatActivity.java (hunk 1 above)
Comment (navarhontes) [reply app/src/main/java/com/courseproject/tindar/ui/chat/ChatActivity.java:179]: No, it's not overriding anything at the moment. I could in theory create an interface for the xml file, but it doesn't seem worth it right now.

**Review by jenniferjinyoungyang — DISMISSED** [review]

**Review by kresimirgotovac — APPROVED** [review]

**Review by candidcalcifer — APPROVED** [review]

**Review by yiwxng — APPROVED** [review]
